### ISSUE TITLE
Allow users to register

### ISSUE THREAD

**Issue by devimust** [devimust/easy-bookmark-manager#16]
Give ability for any user to create a new account.

**Comment by amiceli** [comment]
Did you start to work on it ?
If you're ok, I can start to work on it.

**Comment by devimust** [comment]
Not yet, feel free to take a stab :) please include the ability to disable
this functionality in .env file.

**Comment by amiceli** [comment]
ok thanks, I note it.

**Comment by amiceli** [comment]
For registration, do you want server send an email to validate account ?

**Comment by devimust** [comment]
I think so, maybe allow the app to use existing email server to send e.g. via Gmail account (smtp) or another custom smtp. I'll leave up to you to come up with a solution and we can always tweak it later :) if we allow the server hosting the app to send email, we'll run into mail delivery problems if this is installed on shared blacklisted servers.

**Comment by devimust** [comment]
I think so, maybe allow the app to use existing email server to send e.g.
via Gmail account (smtp) or another custom smtp. I'll leave up to you to
come up with a solution and we can always tweak it later :) if we allow the
server hosting the app to send email, we'll run into mail delivery problems
if this is installed on shared blacklisted servers.

**Comment by amiceli** [comment]
If a user is created in admin section, do we send a mail also ?

I think we can allow to enable email verification for register and/or admin creation.
And disable both options.

What do you think about it ?

**Comment by devimust** [comment]
> If a user is created in admin section, do we send a mail also ?
> If configured to do so then yes :)
> 
> What do you think about it ?
> Good idea

Ps. if you'd like you can send me emails directly via rudi.olckers@gmail.com

**Comment by devimust** [comment]
Issue fixed in #28
