### ISSUE TITLE
gulp --production not working

### ISSUE THREAD

**Issue by devimust** [devimust/easy-bookmark-manager#22]
@amiceli, can you please investigate the following error - the recent translation updates appear to have broken the `gulp --production` output. A `gulp` or `gulp watch` works however.

![image](https://cloud.githubusercontent.com/assets/12205479/19466683/351257c0-9569-11e6-9e51-e5571870c72e.png)

Thanks

**Comment by amiceli** [comment]
ok I'll check it asap.

**Comment by devimust** [comment]
I had a more detailed look and think it's related to the gulpfile minifying already minified js resulting in a bad vendor.js.

Update:
For vendor.js I'll try to use mix.combine instead of mix.scripts - 
`If you intend to concatenate multiple pre-minified vendor libraries, such as jQuery, instead consider using mix.combine(). This will combine the files, while omitting the source map and minification steps. As a result, compile times will drastically improve.` https://laravel.com/docs/5.3/elixir#working-with-scripts

**Comment by amiceli** [comment]
Yes I found it to.
I'll push fix in few minutes.

**Comment by devimust** [comment]
Awesome, thanks :+1:
