### ISSUE TITLE
How to set up bookmark-manager?

### ISSUE THREAD

**Issue by wogho** [devimust/easy-bookmark-manager#34]
OS: Centos 7
PHP: 7.4.10
gulp: CLI version: 2.3.0

php artisan migrate --seed

```
PHP Warning:  require(/root/easy-bookmark-manager/bootstrap/../vendor/autoload.php): failed to open stream: 
No such file or directory in /root/easy-bookmark-manager/bootstrap/autoload.php on line 17

PHP Fatal error:  require(): Failed opening required '/root/easy-bookmark-manager/bootstrap/../vendor/autoload.php' 
(include_path='.:/usr/share/pear:/usr/share/php') in /root/easy-bookmark-manager/bootstrap/autoload.php on line 17
```

line17: require __DIR__.'/../vendor/autoload.php';

I am a beginner. I have never used php or docker etc..

**Comment by dnldp55** [comment]
I sloved install monolog 
but, I have another problem

**Comment by devimust** [comment]
That looks like a missing install instruction. Usually happens when you haven't run a composer install.
