### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by roswitina** [devimust/easy-bookmark-manager#6]
Where can I login as admin?

![ebm](https://cloud.githubusercontent.com/assets/2253471/15390829/4937a7c8-1dbe-11e6-93ef-fa4fcf3ec6d4.PNG)

**Comment by devimust** [comment]
Hi what os, browser and version are you using?

**Comment by roswitina** [comment]
Windows 10 64bit, Firefox 47.0b6 german 32bit.
Server: Debian 8

**Comment by roswitina** [comment]
With Vidalia and Windows Edge I can login.
Thanks

**Comment by devimust** [comment]
I'm struggling to replicate the issue. I downloaded "MSEdge - Win10TH2" virtualbox VM (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/linux/) and installed Firefox 47.0b6 32bit en-GB (https://ftp.mozilla.org/pub/firefox/releases/47.0b6/win32/en-GB/) and cannot replicate on my local dev rig and my production site. Are you perhaps able to give me more info? Do you see any errors in the console developers log? e.g. open settings (top right hand burger icon) -> developer -> web console and refresh the page. Alternatively are you able to provide me with a public url where this is installed?

**Comment by devimust** [comment]
Please double check that your webserver user has write access to these folders:
`storage/`
`bootstrap/cache/`

**Comment by roswitina** [comment]
I think I'm crazy. Now everything works in Firefox. But I do not know what I could have changed.

My file permissions:
root @ easybm: / var / www / ebm # ls -al
total 232
drwxr-xr-x 13 www-data www-data 4096 May 19 09:15.
drwxr-xr-x 8 www-data www-data 4096 May 20 08:22 ..
-rwxr-xr-x 1 www-data www-data 221 May 19 09:15 .env
-rwxr-xr-x 1 www-data www-data 207 May 19 06:52 .env.example
-rwxr-xr-x 1 www-data www-data 163 May 19 06:52 .env.travis
drwxr-xr-x 8 www-data www-data 4096 May 19 06:52 .git
-rwxr-xr-x 1 www-data www-data 61 May 19 06:52 .gitattributes
-rwxr-xr-x 1 www-data www-data 50 May 19 06:52 .gitignore
-rwxr-xr-x 1 www-data www-data 95 May 19 06:52 .htaccess
-rwxr-xr-x 1 www-data www-data 92 May 19 06:52 .jshintignore
-rwxr-xr-x 1 www-data www-data 241 May 19 06:52 .travis.yml
-rwxr-xr-x 1 www-data www-data 2319 May 19 06:52 README.md
drwxr-xr-x 10 www-data www-data 4096 May 19 06:52 app
-rwxr-xr-x 1 www-data www-data 1646 May 19 06:52 artisan
drwxr-xr-x 3 www-data www-data 4096 May 19 06:52 bootstrap
-rwxr-xr-x 1 www-data www-data 1268 May 19 06:52 composer.json
-rwxr-xr-x 1 www-data www-data 112800 May 19 06:52 composer.lock
drwxr-xr-x 2 www-data www-data 4096 May 19 06:52 config
drwxr-xr-x 5 www-data www-data 4096 May 19 06:52 database
-rwxr-xr-x 1 www-data www-data 529 May 19 06:52 elixir-extensions.js
-rwxr-xr-x 1 www-data www-data 2235 May 19 06:52 gulpfile.js
-rwxr-xr-x 1 www-data www-data 463 May 19 06:52 package.json
-rwxr-xr-x 1 www-data www-data 951 May 19 06:52 phpunit.xml
drwxr-xr-x 3 www-data www-data 4096 May 19 06:52 plugins
drwxr-xr-x 7 www-data www-data 4096 May 19 06:52 public
-rwxr-xr-x 1 www-data www-data 1926 May 19 06:52 readme.md
drwxr-xr-x 5 www-data www-data 4096 May 19 06:52 resources
-rwxr-xr-x 1 www-data www-data 567 May 19 06:52 server.php
drwxr-xr-x 5 www-data www-data 4096 May 19 06:52 storage
drwxr-xr-x 2 www-data www-data 4096 May 19 06:52 tests
drwxr-xr-x 30 www-data www-data 4096 May 19 09:14 vendor

**Comment by roswitina** [comment]
I now try me the latest version of Github.

I noticed that when I creating a new user the password show as plain text on the MYSQL table. If I then edit the user and write the same password enter again, it is hashed.

In my work while creating a bookmark either "save" or "save and close". There is only a small circle with moving points. After pressing F5 and the Back - Button I see the link but in the overview.

**Comment by roswitina** [comment]
Would it be possible that additionally marked bookmarks as public or private. It could be used to share certain bookmarks in a workgroup.

**Comment by roswitina** [comment]
Where can I see the logged on user?

**Comment by devimust** [comment]
> Where can I see the logged on user?

I can add that as a feature, this project started out as a means to get around Google Chrome's rapid change in how they do bookmarks. Laravel's authentication works pretty well out of the box so adding this should be straight forward. You are more than welcome to also develop on this to add these features :)

**Comment by devimust** [comment]
> Would it be possible that additionally marked bookmarks as public or private. It could be used to share certain bookmarks in a workgroup.

That would be a nice feature to add :smile:

**Comment by roswitina** [comment]
I've never programmed and can unfortunately not. I can currently only offer my help for testing.

**Comment by devimust** [comment]
Created issue #12 and #13
